SEED: 7
DEBUG: False
LOG_FREQ_STEP: 100
LOG_FREQ_EPOCH: 5

TRAINER:
  LR: 0.05
  BATCH_SIZE: 128
  EPOCHS: 75
  OPTIMIZER:
    TYPE: 'sdg'
    MOMENTUM: 0.9
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    TYPE: 'multistep'
    GAMMA: 0.1
    MILESTONES: [25, 50]

MODEL:
  TYPE: 'resnet'
  RESNET_SIZE: 18
  PACKED: False
  NUM_ESTIMATORS: 4
  ALPHA: 2
  GAMMA: 2
  OUT_CHANNELS: 10
  IN_CHANNELS: 3
  LOSS_TYPE: 'CrossEntropyLoss'

DATALOADER:
  NUM_WORKER: 2
  SHUFFLE: True

